### ISSUE TITLE
have a well-seeded database

### ISSUE THREAD

**Issue by andrewlin1368** [binaryballer33/grace_shopper_e_commerce#13]

**Comment by binaryballer33** [comment]
Pull Request for seeding the database
 https://github.com/binaryballer33/grace_shopper_e_commerce/pull/19

**Comment by binaryballer33** [comment]
## [Prisma Version Of Pull Request for seeding the database](https://github.com/binaryballer33/grace_shopper_e_commerce/pull/21/files)

**Comment by binaryballer33** [comment]
database seeded successfully
