### ISSUE TITLE
create db schema

### ISSUE THREAD

**Issue by binaryballer33** [binaryballer33/grace_shopper_e_commerce#3]

**Comment by andrewlin1368** [comment]
[Untitled document.pdf](https://github.com/binaryballer33/grace_shopper_e_commerce/files/14212059/Untitled.document.pdf)

**Comment by andrewlin1368** [comment]
model User {
  id        Int      @id @default(autoincrement())
  firstName String
  lastName  String
  username  String  @unique
  password  String
  type      UserType
  orders    Order[]
}

enum UserType {
  admin
  customer
}

model Product {
  id          Int           @id @default(autoincrement())
  name        String
  description String
  image       String
  count       Int
  price       Int
}

model Order {
  id         Int           @id @default(autoincrement())
  userId     Int
  user       User          @relation(fields: [userId], references: [id])
  orderDetails OrderDetail[]
}

model OrderDetail {
  orderId   Int
  order     Order   @relation(fields: [orderId], references: [id])
  productId Int
  product   Product @relation(fields: [productId], references: [id])
  quantity  Int

  @@id([orderId, productId])
}

**Comment by binaryballer33** [comment]
*** UPDATE  TO DATABASE SCHEMA USING PRISMA ***

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model users {
  id        Int      @id @default(autoincrement())
  firstname String   @db.VarChar(255)
  lastname  String   @db.VarChar(255)
  username  String   @unique @db.VarChar(255)
  password  String   @db.VarChar(255)
  type      userType
  orders    orders[]
}

enum userType {
  admin
  customer
}

model products {
  id              Int               @id @default(autoincrement())
  name            String            @db.VarChar(255)
  description     String            @db.VarChar(255)
  image           String            @db.VarChar(255)
  count           Int
  price           Int
  productsInOrder productsInOrder[]
}

model orders {
  id              Int               @id @default(autoincrement())
  userId          Int
  users           users             @relation(fields: [userId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  createdAt       DateTime          @default(now())
  status          orderStatus
  productsInOrder productsInOrder[]
  total           Float
}

enum orderStatus {
  fulfilled
  inCart
  cancelled
}

model productsInOrder {
  orderId   Int
  orders    orders   @relation(fields: [orderId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  productId Int
  products  products @relation(fields: [productId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  quantity  Int

  @@id([orderId, productId])
}

**Comment by binaryballer33** [comment]
new database schema
